version: '2.2'

services:
  web_1:
    restart: "no"
    image: tomcat
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"

  web_2:
    restart: "no"
    image: tomcat
    volumes:
      - "./tomcat/webapps:/usr/local/tomcat/webapps"

  nginx:
    restart: "no"
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf:/etc/nginx/conf.d"
    links:
      - web_1
      - web_2